name: Deploy static content

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single job for deployment or build process
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Adicione suas etapas de build ou deploy específicas aqui, se houver
      # Por exemplo, você pode adicionar comandos para construir seu projeto ou realizar outras ações necessárias
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build
